// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tegifwrjuvgbeflwhpra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlZ2lmd3JqdXZnYmVmbHdocHJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjQwOTcsImV4cCI6MjA2NzY0MDA5N30.o6F57VXpSZ49tmdk864lQnVJTuMIVrqxipPchY14KJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});